name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          repository: torvalds/linux
          ref: v6.18
          path: linux

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu bc libssl-dev libelf-dev bison flex

      - name: Configure and Build
        run: |
          cd linux
          # 这一步会生成 .config 文件
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- defconfig
          
          # 这一步开始正式编译
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)
